# Generated by Django 6.0.6 on 2026-06-09 12:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('otp_type', models.CharField(choices=[('phone', 'Phone OTP'), ('email', 'Email OTP')], max_length=10)),
                ('purpose', models.CharField(choices=[('login', 'Login'), ('register', 'Registration'), ('reset', 'Password Reset')], default='login', max_length=20)),
                ('code', models.CharField(max_length=6)),
                ('is_verified', models.BooleanField(default=False)),
                ('attempts', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'otps',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone', 'otp_type'], name='otps_phone_5ec43b_idx'), models.Index(fields=['email', 'otp_type'], name='otps_email_bc3a89_idx')],
            },
        ),
    ]
