# Generated by Django 6.0.6 on 2026-06-09 12:24

import apps.signatures.models
import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SignatureAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('analysis_type', models.CharField(choices=[('enrollment', 'Enrollment Analysis'), ('verification', 'Verification Analysis'), ('forensic', 'Forensic Analysis'), ('quality', 'Quality Analysis')], max_length=20)),
                ('overall_score', models.FloatField()),
                ('confidence_score', models.FloatField()),
                ('geometric_consistency', models.FloatField()),
                ('stroke_consistency', models.FloatField()),
                ('pressure_variation', models.FloatField()),
                ('speed_variation', models.FloatField()),
                ('pen_lift_count', models.IntegerField()),
                ('tremor_analysis', models.JSONField(default=dict)),
                ('slant_analysis', models.JSONField(default=dict)),
                ('loop_analysis', models.JSONField(default=dict)),
                ('forgery_indicators', models.JSONField(default=list)),
                ('authenticity_score', models.FloatField()),
                ('skill_level_required', models.CharField(blank=True, max_length=20)),
                ('cnn_features', models.BinaryField(blank=True, null=True)),
                ('siamese_output', models.FloatField(blank=True, null=True)),
                ('ensemble_prediction', models.FloatField(blank=True, null=True)),
                ('processing_time', models.FloatField()),
                ('model_version', models.CharField(max_length=20)),
                ('analysis_timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'signature_analyses',
                'ordering': ['-analysis_timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SignatureCollection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('collection_type', models.CharField(choices=[('personal', 'Personal Collection'), ('department', 'Department Collection'), ('project', 'Project Collection'), ('compliance', 'Compliance Collection')], default='personal', max_length=20)),
                ('max_templates', models.IntegerField(default=20)),
                ('require_approval', models.BooleanField(default=False)),
                ('auto_archive_days', models.IntegerField(default=365)),
                ('is_shared', models.BooleanField(default=False)),
                ('tags', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'signature_collections',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SignatureMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_verifications', models.IntegerField(default=0)),
                ('successful_matches', models.IntegerField(default=0)),
                ('failed_matches', models.IntegerField(default=0)),
                ('fraud_attempts', models.IntegerField(default=0)),
                ('avg_processing_time', models.FloatField(default=0.0)),
                ('avg_similarity_score', models.FloatField(default=0.0)),
                ('avg_confidence_score', models.FloatField(default=0.0)),
                ('consistency_score', models.FloatField(default=0.0)),
                ('reliability_score', models.FloatField(default=0.0)),
                ('daily_usage', models.JSONField(default=dict)),
                ('weekly_trends', models.JSONField(default=dict)),
                ('monthly_summary', models.JSONField(default=dict)),
                ('last_calculated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'signature_metrics',
            },
        ),
        migrations.CreateModel(
            name='SignatureTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('template_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('original_file', models.FileField(upload_to=apps.signatures.models.signature_upload_path, validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'pdf'])])),
                ('processed_image', models.ImageField(blank=True, upload_to=apps.signatures.models.signature_upload_path)),
                ('file_size', models.IntegerField()),
                ('file_format', models.CharField(max_length=10)),
                ('image_hash', models.CharField(max_length=64, unique=True)),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('dpi', models.IntegerField(blank=True, null=True)),
                ('color_mode', models.CharField(blank=True, max_length=20)),
                ('quality_score', models.FloatField(blank=True, null=True)),
                ('quality_level', models.CharField(blank=True, choices=[('poor', 'Poor Quality'), ('fair', 'Fair Quality'), ('good', 'Good Quality'), ('excellent', 'Excellent Quality')], max_length=20)),
                ('clarity_score', models.FloatField(blank=True, null=True)),
                ('completeness_score', models.FloatField(blank=True, null=True)),
                ('feature_vector', models.BinaryField(blank=True, null=True)),
                ('keypoints', models.TextField(default='{}')),
                ('contours', models.TextField(default='{}')),
                ('geometric_features', models.TextField(default='{}')),
                ('texture_features', models.TextField(default='{}')),
                ('stroke_count', models.IntegerField(blank=True, null=True)),
                ('stroke_width_avg', models.FloatField(blank=True, null=True)),
                ('stroke_width_variance', models.FloatField(blank=True, null=True)),
                ('signature_complexity', models.FloatField(blank=True, null=True)),
                ('aspect_ratio', models.FloatField(blank=True, null=True)),
                ('pixel_density', models.FloatField(blank=True, null=True)),
                ('edge_density', models.FloatField(blank=True, null=True)),
                ('symmetry_score', models.FloatField(blank=True, null=True)),
                ('curvature_analysis', models.JSONField(default=dict)),
                ('verification_count', models.IntegerField(default=0)),
                ('match_count', models.IntegerField(default=0)),
                ('success_rate', models.FloatField(default=0.0)),
                ('avg_similarity_score', models.FloatField(default=0.0)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('compliance_flags', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived'), ('processing', 'Processing'), ('failed', 'Processing Failed')], default='processing', max_length=20)),
                ('processing_errors', models.TextField(blank=True)),
                ('tags', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'signature_templates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SignatureTemplateCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'signature_template_collections',
            },
        ),
        migrations.CreateModel(
            name='SignatureVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.IntegerField()),
                ('file_snapshot', models.FileField(upload_to=apps.signatures.models.signature_upload_path)),
                ('features_snapshot', models.BinaryField()),
                ('analysis_snapshot', models.JSONField(default=dict)),
                ('changes_made', models.TextField()),
                ('change_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'signature_versions',
                'ordering': ['-version_number'],
            },
        ),
    ]
