# Generated by Django 6.0.6 on 2026-06-09 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('signatures', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='signaturecollection',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.organization'),
        ),
        migrations.AddField(
            model_name='signaturecollection',
            name='shared_users',
            field=models.ManyToManyField(blank=True, related_name='shared_collections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='signaturecollection',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signature_collections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='signaturetemplate',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.organization'),
        ),
        migrations.AddField(
            model_name='signaturetemplate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signature_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='signaturetemplate',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='signaturemetrics',
            name='template',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='signatures.signaturetemplate'),
        ),
        migrations.AddField(
            model_name='signatureanalysis',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='signatures.signaturetemplate'),
        ),
        migrations.AddField(
            model_name='signaturetemplatecollection',
            name='added_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='signaturetemplatecollection',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signatures.signaturecollection'),
        ),
        migrations.AddField(
            model_name='signaturetemplatecollection',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signatures.signaturetemplate'),
        ),
        migrations.AddField(
            model_name='signatureversion',
            name='changed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='signatureversion',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='signatures.signaturetemplate'),
        ),
        migrations.AddIndex(
            model_name='signaturetemplate',
            index=models.Index(fields=['user', 'status'], name='signature_t_user_id_11f03d_idx'),
        ),
        migrations.AddIndex(
            model_name='signaturetemplate',
            index=models.Index(fields=['organization'], name='signature_t_organiz_268dea_idx'),
        ),
        migrations.AddIndex(
            model_name='signaturetemplate',
            index=models.Index(fields=['image_hash'], name='signature_t_image_h_c0643f_idx'),
        ),
        migrations.AddIndex(
            model_name='signaturetemplate',
            index=models.Index(fields=['quality_score'], name='signature_t_quality_ed4104_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='signaturetemplate',
            unique_together={('user', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='signaturetemplatecollection',
            unique_together={('template', 'collection')},
        ),
        migrations.AlterUniqueTogether(
            name='signatureversion',
            unique_together={('template', 'version_number')},
        ),
    ]
